version: "3"

services:
  db:
    image: postgres:latest
    environment:
      name: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: resliv_travel
    ports:
    - 5432:5432

  webserver:
    image: stelmakhov/telegram_bot:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      DB_URL: jdbc:postgresql://db:5432/resliv_travel
      NAME: #enter bot name
      TOKEN: #enter bot token